/* Floating */
(function () { injectScript([{ "attr": [{ "name": "id", "value": "fixedban" }, { "name": "style", "value": "width:100%;margin:auto;text-align:center;float:none;overflow:hidden;display:scroll;position:fixed;bottom:0;z-index:999;-webkit-transform:translateZ(0);" }], "tag": "div", "inner": "<div style=\"margin-bottom: 2px;\"><center><a href=\"https://plumprush.com/uNcImA\" target=\"_blank\" id=\"close-fixedban\" onclick=\"document.getElementById(&quot;fixedban&quot;).style.display = &quot;none&quot;;\" style=\"cursor:pointer;\"><img alt=\"close\" src=\"https://3.bp.blogspot.com/-ZZSacDHLWlM/VhvlKTMjbLI/AAAAAAAAF2M/UDzU4rrvcaI/s1600/btn_close.gif\" style=\"vertical-align:middle;\" title=\"close\"></a></center></div><div style=\"text-align:center;display:block;max-width:728px;height:auto;overflow:hidden;margin:auto\">\n<center id=\"ad__float\"></center></div>" }], { "target": "body" }); function injectScript(e, t) { let n = t.target; for (let t of e) { let e = t.tag, r = t.inner, o = document.createElement(e); o.innerHTML = r; let c = t.attr; for (let e of c) o.setAttribute(e.name, e.value); document.querySelector(n) && document.querySelector(n).append(o) } } })();

/* HilltopAds Banner */
(function () { injectScript([{ "attr": [], "tag": "script", "inner": "(function(wuprc){var d = document,s = d.createElement('script'),l = d.scripts[d.scripts.length - 1];s.settings = wuprc || {};\ns.src = \"\\/\\/excitableminor.com\\/bJXSV.ssdrGElu0\\/YIW\\/cb\\/CebmA9cu\\/ZIUElZkRPhTgY\\/3UMTTfIpweN\\/zBQQtpN\\/jjcyxDMGjzA\\/3WNWQK\";s.async = true;s.referrerPolicy = 'no-referrer-when-downgrade';l.parentNode.insertBefore(s, l);})({})" }], { "target": "#ad__float" }); function injectScript(e, t) { let n = t.target; for (let t of e) { let e = t.tag, r = t.inner, o = document.createElement(e); o.innerHTML = r; let c = t.attr; for (let e of c) o.setAttribute(e.name, e.value); document.querySelector(n) && document.querySelector(n).append(o) } } })();

/* HilltopAds Popunder */
(function () { injectScript([{ "attr": [], "tag": "script", "inner": "(function(ijddl){var d = document,s = d.createElement('script'),l = d.scripts[d.scripts.length - 1];s.settings = ijddl || {};s.src = \"\\/\\/plumprush.com\\/cLD\\/9w6.bJ2d5XlFSkW\\/Q\\/9HNIjMcYxfMmjUAp3dMTig0t2gNezCEDywMFD_c\\/ze\";s.async = true;s.referrerPolicy = 'no-referrer-when-downgrade';l.parentNode.insertBefore(s, l);})({})" }], { "target": "body" }); function injectScript(e, t) { let n = t.target; for (let t of e) { let e = t.tag, r = t.inner, o = document.createElement(e); o.innerHTML = r; let c = t.attr; for (let e of c) o.setAttribute(e.name, e.value); document.querySelector(n) && document.querySelector(n).append(o) } } })();

/* HilltopAds In-page Push */
(function () { injectScript([{ "attr": [], "tag": "script", "inner": "(function(rvgig){var d = document,s = d.createElement('script'),l = d.scripts[d.scripts.length - 1];s.settings = rvgig || {};s.src = \"\\/\\/excitableminor.com\\/bTX.V\\/sKd\\/Gqls0uY\\/Wjck\\/BeamX9IuOZoUzlpk\\/PRT\\/YH3MMZTSIBwJO\\/DEMBtENejpcIxOMWjHAg4\\/NeA-\";s.async = true;s.referrerPolicy = 'no-referrer-when-downgrade';l.parentNode.insertBefore(s, l);})({})" }], { "target": "body" }); function injectScript(e, t) { let n = t.target; for (let t of e) { let e = t.tag, r = t.inner, o = document.createElement(e); o.innerHTML = r; let c = t.attr; for (let e of c) o.setAttribute(e.name, e.value); document.querySelector(n) && document.querySelector(n).append(o) } } })();

/* Histats */
(function () { injectScript([{ "attr": [{ "name": "type", "value": "text/javascript" }], "tag": "script", "inner": "var _Hasync= _Hasync|| [];_Hasync.push(['Histats.start', '1,4946035,4,0,0,0,00010000']);_Hasync.push(['Histats.fasi', '1']);_Hasync.push(['Histats.track_hits', '']);(function() {var hs = document.createElement('script'); hs.type = 'text/javascript'; hs.async = true;hs.src = ('//s10.histats.com/js15_as.js');(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(hs);})();" }], { "target": "body" }); function injectScript(e, t) { let n = t.target; for (let t of e) { let e = t.tag, r = t.inner, o = document.createElement(e); o.innerHTML = r; let c = t.attr; for (let e of c) o.setAttribute(e.name, e.value); document.querySelector(n) && document.querySelector(n).append(o) } } })();
